"""horario_secullum

Revision ID: 4d8de113b578
Revises: 
Create Date: 2026-02-23 10:25:52.909484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8de113b578'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horario_secullum_numero', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('horario_secullum_nome', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_column('horario_secullum_nome')
        batch_op.drop_column('horario_secullum_numero')

    # ### end Alembic commands ###
